### ISSUE TITLE
[Bug] MakePri fails to generate resource files, resulting in installation failure

### ISSUE THREAD

**Issue by MustardChef** [LSPosed/MagiskOnWSALocal#450]
### Steps to reproduce/复现步骤

1. Clone MagiskOnWSALocal repo and run the script using `./MagiskOnWSA/scripts/run.sh` 
2. Select x64, WIF/Insider Fast, Yes to Root, Magisk, GApps Varient; Pico, MindTheGapps, Remove Amazon Appstore
3. Copy the build from the WSL Network Drive/ WSL Distro storage to a location on the Windows drive
4. Running "Run.bat" to install 
5. Error Shows

### Expected behaviour/预期行为

WSA should install smoothly, without any issue like with the previously built builds

### Actual behaviour/实际行为

Installing MagiskOnWSA....
WsaClient does not exist
                                                                                                                         Deployment operation progress: C:\Users\MCDeltaT\Downloads\WSA_2302.40000.8.0_x64_Release-Nightly-with-magisk-981ccab    Processing                                                                                                              [o                                                                                                           ]                                                                                                                              NamedResource Not Found.
. Check that the string resource is defined and that there
C:\Users\MCDeltaT\Downloads\WSA_2302.40000.8.0_x64_Release-Nightly-with-magisk-981ccabb(25210)-canary-MindTheGapps-13
.0-RemovedAmazon\AppxManifest.xml(79,27): error 0x80073B17: Cannot register the
MicrosoftCorporationII.WindowsSubsystemForAndroid_2302.40000.8.0_x64__8wekyb3d8bbwe package because the following
error was encountered while determining whether the ms-resource:WsaDisplayName string resource could be localized:
NamedResource Not Found.
. Check that the string resource is defined and that there is at least one instance defined in the resources.pri file
contained in this package.
NOTE: For additional information, look for [ActivityId] 903ba5dc-5ef4-0000-67f8-4e90f45ed901 in the Event Log or use
the command line Get-AppPackageLog -ActivityID 903ba5dc-5ef4-0000-67f8-4e90f45ed901
At C:\Users\MCDeltaT\Downloads\WSA_2302.40000.8.0_x64_Release-Nightly-with-magisk-981ccabb(25210)-canary-MindTheGapps
-13.0-RemovedAmazon\Install.ps1:139 char:1
+ Add-AppxPackage -ForceApplicationShutdown -ForceUpdateFromAnyVersion  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\Jay Ra...ppxManifest.xml:String) [Add-AppxPackage], IOException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

All Done!
Press any key to exit

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

58e17da

### Linux distribution info/Linux 发行版信息

PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
KERNAL= 5.15.90.1-microsoft-standard-WSL2

### Windows version/Windows 版本

10.0.22621.1413

### Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type WIF --magisk-ver canary --gapps-brand MindTheGapps --gapps-variant pico --remove-amazon --root-sol magisk --compress    --compress-format zip
INFO: Architecture: x64
INFO: Release Type: WIF
INFO: Magisk Version: canary
INFO: GApps Brand: MindTheGapps
INFO: GApps Variant: pico
INFO: Root Solution: magisk
INFO: Compress Format: zip
Build: RELEASE_TYPE=Insider Fast

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>

[//]: <> (Don't modify above)

```
Time                      ID           Message
----                      --           -------
25/03/2023 18:01:34       603          Started deployment Register operation on a package with main parameter
                                       AppxManifest.xml and Options
                                       ForceApplicationShutdownOption,DevelopmentModeOption,ForceUpdateFromAnyVersion
                                       and 0. See http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing
                                       app deployment issues.
25/03/2023 18:01:34       216          App manifest validation warning: Declared namespace
                                       http://schemas.microsoft.com/developer/appx/2015/build is inapplicable, it will
                                       be ignored during manifest processing.
25/03/2023 18:01:34       10002        Creating Resiliency File C:\ProgramData\Microsoft\Windows\AppRepository\7841aea9
                                       -97fe-4de3-982a-5b92620321b0_S-1-5-21-3274399036-2637223480-2773644710-1001_3.rs
                                       lc for Register Operation on Package MicrosoftCorporationII.WindowsSubsystemForA
                                       ndroid_2302.40000.8.0_x64__8wekyb3d8bbwe.
25/03/2023 18:01:34       607          Deployment Register operation on package MicrosoftCorporationII.WindowsSubsystem
                                       ForAndroid_2302.40000.8.0_x64__8wekyb3d8bbwe has been de-queued and is running
                                       for user SID S-1-5-21-3274399036-2637223480-2773644710-1001.
25/03/2023 18:01:34       854          Successfully added the following uri(s) to be processed:  C:\Users\MCDeltaT\Do
                                       wnloads\WSA_2302.40000.8.0_x64_Release-Nightly-with-magisk-981ccabb(25210)-canar
                                       y-MindTheGapps-13.0-RemovedAmazon\AppxManifest.xml.
25/03/2023 18:01:35       855          Finished resolving action lists. DeploymentRequest action lists:
                                       addPackageList: MicrosoftCorporationII.WindowsSubsystemForAndroid_2302.40000.8.0
                                       _x64__8wekyb3d8bbwe.
25/03/2023 18:01:35       333          C:\Users\MCDeltaT\Downloads\WSA_2302.40000.8.0_x64_Release-Nightly-with-magisk
                                       -981ccabb(25210)-canary-MindTheGapps-13.0-RemovedAmazon\AppxManifest.xml(79,27):
                                        error 0x80073B17: Cannot register the MicrosoftCorporationII.WindowsSubsystemFo
                                       rAndroid_2302.40000.8.0_x64__8wekyb3d8bbwe package because the following error
                                       was encountered while determining whether the ms-resource:WsaDisplayName string
                                       resource could be localized: NamedResource Not Found.
                                       . Check that the string resource is defined and that there is at least one
                                       instance defined in the resources.pri file contained in this package.
25/03/2023 18:01:35       6902         AppxManifest.xml(78,6): error 0x80073B17: Cannot register the MicrosoftCorporati
                                       onII.WindowsSubsystemForAndroid_2302.40000.8.0_x64__8wekyb3d8bbwe package
                                       because the following error was encountered while parsing the App application:
                                       NamedResource Not Found.
                                       .  Try again and contact the package publisher if the problem persists.
25/03/2023 18:01:35       6901         AppxManifest.xml(96,10): error 0x80073B17: Cannot register the MicrosoftCorporat
                                       ionII.WindowsSubsystemForAndroid_2302.40000.8.0_x64__8wekyb3d8bbwe package
                                       because the following error was encountered while parsing the
                                       windows.appExecutionAlias Extension element: NamedResource Not Found.
                                       .  Try again and contact the package publisher if the problem persists.
25/03/2023 18:01:35       6800         AppxManifest.xml(98,14): error 0x80073B17: Cannot register the
                                       MicrosoftCorporationII.WindowsSubsystemForAndroid package because the following
                                       error was encountered while parsing the windows.appExecutionAlias extension:
                                       NamedResource Not Found.
                                       .  Try again and contact the package publisher if the problem persists.
25/03/2023 18:01:35       303          error 0x80073B17: While preparing to process the request, the system failed to
                                       register the windows.appExecutionAlias extension due to the following error:
                                       NamedResource Not Found.
                                       .
25/03/2023 18:01:35       300          error 0x80073B17: Cannot register the
                                       MicrosoftCorporationII.WindowsSubsystemForAndroid_8wekyb3d8bbwe package due to
                                       the following error: NamedResource Not Found.
                                       .
25/03/2023 18:01:35       605          The last successful state reached was MutablePackageDirectoryAdd. Failure
                                       occurred before reaching the next state MachineRegisterAdd. hr: 0x80073CF6
25/03/2023 18:01:35       401          Deployment Register operation with target volume C: on Package MicrosoftCorporat
                                       ionII.WindowsSubsystemForAndroid_2302.40000.8.0_x64__8wekyb3d8bbwe from:
                                       (AppxManifest.xml)  failed with error 0x80073CF6. See
                                       http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app
                                       deployment issues.
25/03/2023 18:01:35       698          Deployment Register operation with target volume C: on Package MicrosoftCorporat
                                       ionII.WindowsSubsystemForAndroid_2302.40000.8.0_x64__8wekyb3d8bbwe from:
                                       (AppxManifest.xml)  failed with error 0x80073CF6. See
                                       http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app
                                       deployment issues.
25/03/2023 18:01:35       404          AppX Deployment operation failed for package MicrosoftCorporationII.WindowsSubsy
                                       stemForAndroid_2302.40000.8.0_x64__8wekyb3d8bbwe with error 0x80073CF6. The
                                       specific error text for this failure is: C:\Users\MCDeltaT\Downloads\WSA_2302.
                                       40000.8.0_x64_Release-Nightly-with-magisk-981ccabb(25210)-canary-MindTheGapps-13
                                       .0-RemovedAmazon\AppxManifest.xml(79,27): error 0x80073B17: Cannot register the
                                       MicrosoftCorporationII.WindowsSubsystemForAndroid_2302.40000.8.0_x64__8wekyb3d8b
                                       bwe package because the following error was encountered while determining
                                       whether the ms-resource:WsaDisplayName string resource could be localized:
                                       NamedResource Not Found.
                                       . Check that the string resource is defined and that there is at least one
                                       instance defined in the resources.pri file contained in this package.
25/03/2023 18:01:35       471          error 0x5: Deleting file \\?\C:\Program Files\WindowsApps\Deleted\MicrosoftCorpo
                                       rationII.WindowsSubsystemForAndroid_2302.40000.6.0_x64__8wekyb3d8bbwee4ef9bca-6d
                                       ea-49cc-b498-877a21bac2da\lxutil.dll failed.
25/03/2023 18:01:35       471          error 0x5: Deleting file \\?\C:\Program Files\WindowsApps\Deleted\MicrosoftCorpo
                                       rationII.WindowsSubsystemForAndroid_2302.40000.6.0_x64__8wekyb3d8bbwee4ef9bca-6d
                                       ea-49cc-b498-877a21bac2da\wslcoredeps.dll failed.
25/03/2023 18:01:35       471          error 0x5: Deleting file \\?\C:\Program Files\WindowsApps\Deleted\MicrosoftCorpo
                                       rationII.WindowsSubsystemForLinux_1.0.0.0_x64__8wekyb3d8bbwe1127e998-01db-4239-9
                                       460-f5b07ed7ee66\lxutil.dll failed.
25/03/2023 18:01:35       493          There were 1 additional files that failed to be deleted under the folder
                                       \\?\C:\Program Files\WindowsApps\Deleted.
```
[//]: <> (Don't modify below)
</details>

**Comment by MustardChef** [comment]
This could also be an isolated problem that is only applicable to my PC, so please can you test this and confirm

**Comment by Howard20181** [comment]
This issue was fixed before, please update the scripts.
Please rename the output folder to a shorter name.

**Comment by MustardChef** [comment]
> This issue was fixed before, please update the scripts. Please rename the output folder to a shorter name.
Well, I did freshly reinstall WSL and Debian today and made sure to delete any pervious clones. Also, renaming the output folder does not help either.

**Comment by Howard20181** [comment]
`WsaClient does not exist` is just a warning. It has no effect on whether the installation is successful or not.
The reason for your installation failure is that the content of `resources.pri` is incorrect.
This may be caused by `MakePri.ps1` failing to run, if your WSA setup does not require localization only English you can delete this file before running the install script.

You need to delete the folder for this failed installation and regenerate it before reinstalling.

**Comment by Howard20181** [comment]
The resource merge should have been fixed by this commit.
https://github.com/LSPosed/MagiskOnWSALocal/commit/87ec298263f5fe1d2eb8ca498ecaf78c544a081e

**Comment by MustardChef** [comment]
It looks like MakePri.ps1 does run without any problems, but the error still persists. This is weird, because it also happens when I build and try to install a build on another PC

**Comment by Howard20181** [comment]
What is the size of `resources.pri` after running `MakePri.ps1`?

**Comment by MustardChef** [comment]
1KB, which is surprisingly low

**Comment by Almighty188** [comment]
Same issue here and may have to do with WSA on the RP, Fast and Slow channels all now on v2302.40000.8.0, it was working correctly when WSA was still on v2302.40000.6.0.

![image](https://user-images.githubusercontent.com/78993393/227737674-52577262-c9b1-4dda-b2aa-a37f4ac0a5fa.png)

**Comment by Howard20181** [comment]
On my end, 2302.40000.8 work well with localization settings.

**Comment by Howard20181** [comment]
@MustardChef 
> 1KB, which is surprisingly low (or not)

The correct size for 2302.40000.8 is ~878KB.
`MakePri.ps1` may has some bug.

**Comment by MustardChef** [comment]
I have spoken to 3 other people who have also encounterd the same problem

**Comment by Howard20181** [comment]
Are you familiar with PowerShell?
Try editing `MakePri.ps1` so that it doesn't exit at the end and doesn't delete the w unsuccessfully merged files and see what happens.

Or, wait for me to edit and upload. You will need to regenerate the WSA installation file.

**Comment by Almighty188** [comment]
Is the MakePri.ps1 supposed to be in the same directory as Install.ps1 and Run.bat because I don't even have a MakePri.ps1:
![image](https://user-images.githubusercontent.com/78993393/227738083-79104c39-7a44-4c88-bb5c-306278884f7b.png)

**Comment by Howard20181** [comment]
@Almighty188 
> Is the MakePri.ps1 supposed to be in the same directory as Install.ps1 and Run.bat

It will automatically delete itself after it has been run once, because in theory resource merging is only needed once.

**Comment by Howard20181** [comment]
Run this script under the freshly generated installation file to see what happens (remember to change the suffix to ps1).
[MakePri.debug.ps1.txt](https://github.com/LSPosed/MagiskOnWSALocal/files/11069930/MakePri.debug.ps1.txt)

**Comment by Almighty188** [comment]
> @Almighty188
> 
> > Is the MakePri.ps1 supposed to be in the same directory as Install.ps1 and Run.bat
> 
> It will automatically delete itself after it has been run once, because in theory resource merging is only needed once.

My previous build of WSA v2302.40000.6.0 on March 18, 2023 actually still has the MakePri.ps1.  I'll regenerate the installation file and post the results in a few minutes.

**Comment by Howard20181** [comment]
> > @Almighty188
> > > Is the MakePri.ps1 supposed to be in the same directory as Install.ps1 and Run.bat
> > 
> > 
> > It will automatically delete itself after it has been run once, because in theory resource merging is only needed once.
> 
> My previous build of WSA v2302.40000.6.0 on March 18, 2023 actually still has the MakePri.ps1. I'll regenerate the installation file and post the results in a few minutes.

If you have not run the install script it is there, if you have run it it will be deleted, this is normal behavior.

**Comment by Almighty188** [comment]
> 

I ran Run.bat on it but not Install.ps1 as it was the working WSA.

**Comment by Howard20181** [comment]
> > 
> 
> I ran Run.bat on it but not Install.ps1 as it was the working WSA.

The entire call process looks like this
Run.bat -> Install.ps1 -> MakePri.ps1

**Comment by Howard20181** [comment]
The Install.ps1 will check if MakePri.ps1 exists and if it exists then run it.
MakePri.ps1 will self-delete after running so it can prevent running twice.

**Comment by Howard20181** [comment]
Now we need to figure out why MakePri.exe is generating the wrong resource file.

**Comment by MustardChef** [comment]
WARNING: Failed to merge resources from pri
Trying to dump....


    Directory: C:\Users\MCDeltaT\Downloads\WSA_2302.40000.8.0_x64_Release-Nightly-with-magisk-981ccabb(25210)-canary-
    MindTheGapps-13.0-RemovedAmazon


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        25/03/2023     20:19                priinfo
Dumping resources.language-af.pri....

Dumping resources.language-ar.pri....

Dumping resources.language-az-latn.pri....

Dumping resources.language-bg.pri....

Dumping resources.language-bs.pri....

Dumping resources.language-ca.pri....

Dumping resources.language-cs.pri....

Dumping resources.language-cy.pri....

Dumping resources.language-da.pri....

Dumping resources.language-de.pri....

Dumping resources.language-el.pri....

Dumping resources.language-es.pri....

Dumping resources.language-et.pri....

Dumping resources.language-eu.pri....

Dumping resources.language-fa.pri....

Dumping resources.language-fi.pri....

Dumping resources.language-fr.pri....

Dumping resources.language-gl.pri....

Dumping resources.language-he.pri....

Dumping resources.language-hi.pri....

Dumping resources.language-hr.pri....

Dumping resources.language-hu.pri....

Dumping resources.language-id.pri....

Dumping resources.language-is.pri....

Dumping resources.language-it.pri....

Dumping resources.language-ja.pri....

Dumping resources.language-ka.pri....

Dumping resources.language-kk.pri....

Dumping resources.language-ko.pri....

Dumping resources.language-lt.pri....

Dumping resources.language-lv.pri....

Dumping resources.language-ms.pri....

Dumping resources.language-nb.pri....

Dumping resources.language-nl.pri....

Dumping resources.language-nn.pri....

Dumping resources.language-pl.pri....

Dumping resources.language-pt.pri....

Dumping resources.language-qps-ploc.pri....

Dumping resources.language-qps-ploca.pri....

Dumping resources.language-qps-plocm.pri....

Dumping resources.language-ro.pri....

Dumping resources.language-ru.pri....

Dumping resources.language-sk.pri....

Dumping resources.language-sl.pri....

Dumping resources.language-sq.pri....

Dumping resources.language-sr-cyrl.pri....

Dumping resources.language-sr-latn.pri....

Dumping resources.language-sv.pri....

Dumping resources.language-th.pri....

Dumping resources.language-tr.pri....

Dumping resources.language-uk.pri....

Dumping resources.language-vi.pri....

Dumping resources.language-zh-hans.pri....

Dumping resources.language-zh-hant.pri....

Dumping resources.pri....

Dumping resources.scale-100.pri....

Dumping resources.scale-125.pri....

Dumping resources.scale-150.pri....

Dumping resources.scale-400.pri....

Dumping resources....

Creating pri from dumps....


Language : af-za


Language : ar-sa


Language : az-latn-az


Language : bg-bg


Language : bs-latn-ba


Language : ca-es


Language : cs-cz


Language : cy-gb


Language : da-dk


Language : de-de


Language : el-gr

Cannot convert argument "0", with value: "System.Object[]", for "ImportNode" to type "System.Xml.XmlNode": "Cannot
convert the "System.Object[]" value of type "System.Object[]" to type "System.Xml.XmlNode"."
At C:\Users\MCDeltaT\Downloads\WSA_2302.40000.8.0_x64_Release-Nightly-with-magisk-981ccabb(25210)-canary-MindTheGapps
-13.0-RemovedAmazon\MakePri.ps1:52 char:9
+         $newNode = $ProjectXml.ImportNode($Resource, $true)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodArgumentConversionInvalidCastArgument


Language : el-gr


Language : et-ee


Language : eu-es


Language : fa-ir


Language : fi-fi

Cannot convert argument "0", with value: "System.Object[]", for "ImportNode" to type "System.Xml.XmlNode": "Cannot
convert the "System.Object[]" value of type "System.Object[]" to type "System.Xml.XmlNode"."
At C:\Users\MCDeltaT\Downloads\WSA_2302.40000.8.0_x64_Release-Nightly-with-magisk-981ccabb(25210)-canary-MindTheGapps
-13.0-RemovedAmazon\MakePri.ps1:52 char:9
+         $newNode = $ProjectXml.ImportNode($Resource, $true)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodArgumentConversionInvalidCastArgument


Language : fi-fi


Language : gl-es


Language : he-il


Language : hi-in


Language : hr-hr


Language : hu-hu


Language : id-id


Language : is-is


Language : it-it


Language : ja-jp


Language : ka-ge


Language : kk-kz


Language : ko-kr


Language : lt-lt


Language : lv-lv


Language : ms-my


Language : nb-no


Language : nl-nl


Language : nn-no


Language : pl-pl

Cannot convert argument "0", with value: "System.Object[]", for "ImportNode" to type "System.Xml.XmlNode": "Cannot
convert the "System.Object[]" value of type "System.Object[]" to type "System.Xml.XmlNode"."
At C:\Users\MCDeltaT\Downloads\WSA_2302.40000.8.0_x64_Release-Nightly-with-magisk-981ccabb(25210)-canary-MindTheGapps
-13.0-RemovedAmazon\MakePri.ps1:52 char:9
+         $newNode = $ProjectXml.ImportNode($Resource, $true)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodArgumentConversionInvalidCastArgument


Language : pl-pl


Language : qps-ploc


Language : qps-ploca


Language : qps-plocm


Language : ro-ro


Language : ru-ru


Language : sk-sk


Language : sl-si


Language : sq-al


Language : sr-cyrl-rs


Language : sr-latn-rs


Language : sv-se


Language : th-th


Language : tr-tr


Language : uk-ua


Language : vi-vn


Language : zh-cn


Language : zh-tw


Scale : 100


Scale : 125


Scale : 150


Scale : 400

**Comment by MustardChef** [comment]
This is what shows when ``MakePri.ps1`` is run

**Comment by Howard20181** [comment]
Can't see the problem
The problem occurs in "Creating pri from dumps ...." but there is no error in this sentence

**Comment by Howard20181** [comment]
Maybe we need to run this line manually at the command line to see what happens.
https://github.com/LSPosed/MagiskOnWSALocal/blob/c889b66e93c4e31c7ab1ba11acedd5cd648621e8/installer/MakePri.ps1#L36

**Comment by MustardChef** [comment]
> Maybe we need to run this line manually at the command line to see what happens.
> 
> https://github.com/LSPosed/MagiskOnWSALocal/blob/c889b66e93c4e31c7ab1ba11acedd5cd648621e8/installer/MakePri.ps1#L36

Should I run this line manually?

**Comment by Howard20181** [comment]
Run this
[MakePri.debug.ps1.txt](https://github.com/LSPosed/MagiskOnWSALocal/files/11070016/MakePri.debug.ps1.txt)

**Comment by Howard20181** [comment]
Run this
[MakePri.debug.ps1.txt](https://github.com/LSPosed/MagiskOnWSALocal/files/11070021/MakePri.debug.ps1.txt)
You need to regenerate

**Comment by Almighty188** [comment]
This is after a fresh build after deleting the download folder, git pull and ./scripts/run.sh:
 Generate info
WSA_2302.40000.8.0_x64_Release-Nightly-with-magisk-25.2(25200)-stable-MindTheGapps-13.0

Finishing building....
done

Cleanup Work Directory
done
root@Dell-XPS15-9570:/mnt/c/Users/vince/Desktop/Windows Subsystem for Android/MagiskOnWSALocal#

![image](https://user-images.githubusercontent.com/78993393/227739292-c1683ced-2b00-4029-8d06-4f460fdec11b.png)

With MakePri.debug.ps1 added:
![image](https://user-images.githubusercontent.com/78993393/227739554-37e02c53-1bdb-45e6-b254-5b6350491c54.png)

After MakePri.debug.ps1 is ran:
![image](https://user-images.githubusercontent.com/78993393/227740388-36bf53cd-683e-4154-b6fa-15066ba2b1f1.png)

**Comment by Almighty188** [comment]
That's with the first MakePri.debug.ps1 from 52 minutes ago... Will regenerate and provide output with the newer MakePri.debug.ps1 from 3 minutes ago.

**Comment by MustardChef** [comment]
This is what I get using the latest MakePri.ps1

WARNING: Failed to merge resources from pri
Trying to dump....


    Directory: C:\Users\MCDeltaT\Downloads\WSA_2302.40000.8.0_x64_Release-Nightly-with-magisk-981ccabb(25210)-canary-
    MindTheGapps-13.0-RemovedAmazon


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        25/03/2023     20:37                priinfo
Dumping resources.language-af.pri....

Dumping resources.language-ar.pri....

Dumping resources.language-az-latn.pri....

Dumping resources.language-bg.pri....

Dumping resources.language-bs.pri....

Dumping resources.language-ca.pri....

Dumping resources.language-cs.pri....

Dumping resources.language-cy.pri....

Dumping resources.language-da.pri....

Dumping resources.language-de.pri....

Dumping resources.language-el.pri....

Dumping resources.language-es.pri....

Dumping resources.language-et.pri....

Dumping resources.language-eu.pri....

Dumping resources.language-fa.pri....

Dumping resources.language-fi.pri....

Dumping resources.language-fr.pri....

Dumping resources.language-gl.pri....

Dumping resources.language-he.pri....

Dumping resources.language-hi.pri....

Dumping resources.language-hr.pri....

Dumping resources.language-hu.pri....

Dumping resources.language-id.pri....

Dumping resources.language-is.pri....

Dumping resources.language-it.pri....

Dumping resources.language-ja.pri....

Dumping resources.language-ka.pri....

Dumping resources.language-kk.pri....

Dumping resources.language-ko.pri....

Dumping resources.language-lt.pri....

Dumping resources.language-lv.pri....

Dumping resources.language-ms.pri....

Dumping resources.language-nb.pri....

Dumping resources.language-nl.pri....

Dumping resources.language-nn.pri....

Dumping resources.language-pl.pri....

Dumping resources.language-pt.pri....

Dumping resources.language-qps-ploc.pri....

Dumping resources.language-qps-ploca.pri....

Dumping resources.language-qps-plocm.pri....

Dumping resources.language-ro.pri....

Dumping resources.language-ru.pri....

Dumping resources.language-sk.pri....

Dumping resources.language-sl.pri....

Dumping resources.language-sq.pri....

Dumping resources.language-sr-cyrl.pri....

Dumping resources.language-sr-latn.pri....

Dumping resources.language-sv.pri....

Dumping resources.language-th.pri....

Dumping resources.language-tr.pri....

Dumping resources.language-uk.pri....

Dumping resources.language-vi.pri....

Dumping resources.language-zh-hans.pri....

Dumping resources.language-zh-hant.pri....

Dumping resources.pri....

Dumping resources.scale-100.pri....

Dumping resources.scale-125.pri....

Dumping resources.scale-150.pri....

Dumping resources.scale-400.pri....

Dumping resources....

WARNING: !!!STOP HERE FOR DEBUG!!!
Run  makepri.exe new /pr .\priinfo /cf .\xml\priconfig.xml /of .\resources.pri /mn .\AppxManifest.xml /o at command line!!!


PS C:\Users\MCDeltaT\Downloads\WSA_2302.40000.8.0_x64_Release-Nightly-with-magisk-981ccabb(25210)-canary-MindTheGapps-13.0-RemovedAmazon> ./makepri.exe new /pr .\priinfo /cf .\xml\priconfig.xml /of .\resources.pri /mn .\AppxManifest.xml /o
Index Pass Completed.

Finished building
Version: 1.0
Resource Map Name: MicrosoftCorporationII.WindowsSubsystemForAndroid
Named Resources: 0
Resource Candidates: 0
Successfully Completed

**Comment by Howard20181** [comment]
The normal output is
![image](https://user-images.githubusercontent.com/40033067/227740768-fce1359b-8e2d-479e-b791-83744a3829ae.png)

**Comment by Howard20181** [comment]
In your folder "priinfo" after the dump is empty?

**Comment by Howard20181** [comment]
After dumping of pri, priinfo will be full of XML.

**Comment by Almighty188** [comment]
Output using MakePri.debug.ps1 from https://github.com/LSPosed/MagiskOnWSALocal/issues/450#issuecomment-1483916089
<img width="847" alt="image" src="https://user-images.githubusercontent.com/78993393/227741232-393dad66-1f01-4460-997d-f642381be6ef.png">

**Comment by Howard20181** [comment]
> Output using MakePri.debug.ps1 from [#450 (comment)](https://github.com/LSPosed/MagiskOnWSALocal/issues/450#issuecomment-1483916089) <img alt="image" width="847" src="https://user-images.githubusercontent.com/78993393/227741232-393dad66-1f01-4460-997d-f642381be6ef.png">

Here's the test version I gave you
Can't you see that it says "!!!! !!!STOP HERE FOR DEBUG!!!" ?

**Comment by Almighty188** [comment]
.\makepri.exe new /pr .\priinfo /cf .\xml\priconfig.xml /of .\resources.pri /mn .\AppxManifest.xml /o
Index Pass Completed.

Finished building
Version: 1.0
Resource Map Name: MicrosoftCorporationII.WindowsSubsystemForAndroid
Named Resources: 0
Resource Candidates: 0
Successfully Completed
PS C:\Users\vince\Desktop\Windows Subsystem for Android\MagiskOnWSALocal\output\WSA_2302.40000.8.0_x64_Release-Nightly-with-magisk-25.2(25200)-stable-MindTheGapps-13.0>

**Comment by Howard20181** [comment]
Check the folder priinfo

**Comment by Howard20181** [comment]
It should be
![image](https://user-images.githubusercontent.com/40033067/227741360-b06b8c00-b1b0-41b0-ac8f-7e732fcc153b.png)
after dump

**Comment by Almighty188** [comment]
PS C:\Users\vince\Desktop\Windows Subsystem for Android\MagiskOnWSALocal\output\WSA_2302.40000.8.0_x64_Release-Nightly-with-magisk-25.2(25200)-stable-MindTheGapps-13.0> cd priinfo
PS C:\Users\vince\Desktop\Windows Subsystem for Android\MagiskOnWSALocal\output\WSA_2302.40000.8.0_x64_Release-Nightly-with-magisk-25.2(25200)-stable-MindTheGapps-13.0\priinfo> dir
PS C:\Users\vince\Desktop\Windows Subsystem for Android\MagiskOnWSALocal\output\WSA_2302.40000.8.0_x64_Release-Nightly-with-magisk-25.2(25200)-stable-MindTheGapps-13.0\priinfo>

**Comment by MustardChef** [comment]
> It should be ![image](https://user-images.githubusercontent.com/40033067/227741360-b06b8c00-b1b0-41b0-ac8f-7e732fcc153b.png) after dump

Nothing is there

**Comment by Howard20181** [comment]
Now we should check why it dumps failed.

**Comment by Howard20181** [comment]
Run this
[MakePri.debug.ps1.txt](https://github.com/LSPosed/MagiskOnWSALocal/files/11070129/MakePri.debug.ps1.txt)

**Comment by MustardChef** [comment]
> Run this [MakePri.debug.ps1.txt](https://github.com/LSPosed/MagiskOnWSALocal/files/11070129/MakePri.debug.ps1.txt)

WARNING: Failed to merge resources from pri
Trying to dump....


    Directory: C:\Users\MCDeltaT\Downloads\WSA_2302.40000.8.0_x64_Release-Nightly-with-magisk-981ccabb(25210)-canary-
    MindTheGapps-13.0-RemovedAmazon


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        25/03/2023     21:06                priinfo
Dumping resources.language-af.pri....

WARNING: Dumping resources.language-af.pri failed
Dumping resources.language-ar.pri....

WARNING: Dumping resources.language-ar.pri failed
Dumping resources.language-az-latn.pri....

WARNING: Dumping resources.language-az-latn.pri failed
Dumping resources.language-bg.pri....

WARNING: Dumping resources.language-bg.pri failed
Dumping resources.language-bs.pri....

WARNING: Dumping resources.language-bs.pri failed
Dumping resources.language-ca.pri....

WARNING: Dumping resources.language-ca.pri failed
Dumping resources.language-cs.pri....

WARNING: Dumping resources.language-cs.pri failed
Dumping resources.language-cy.pri....

WARNING: Dumping resources.language-cy.pri failed
Dumping resources.language-da.pri....

WARNING: Dumping resources.language-da.pri failed
Dumping resources.language-de.pri....

WARNING: Dumping resources.language-de.pri failed
Dumping resources.language-el.pri....

WARNING: Dumping resources.language-el.pri failed
Dumping resources.language-es.pri....

WARNING: Dumping resources.language-es.pri failed
Dumping resources.language-et.pri....

WARNING: Dumping resources.language-et.pri failed
Dumping resources.language-eu.pri....

WARNING: Dumping resources.language-eu.pri failed
Dumping resources.language-fa.pri....

WARNING: Dumping resources.language-fa.pri failed
Dumping resources.language-fi.pri....

WARNING: Dumping resources.language-fi.pri failed
Dumping resources.language-fr.pri....

WARNING: Dumping resources.language-fr.pri failed
Dumping resources.language-gl.pri....

WARNING: Dumping resources.language-gl.pri failed
Dumping resources.language-he.pri....

WARNING: Dumping resources.language-he.pri failed
Dumping resources.language-hi.pri....

WARNING: Dumping resources.language-hi.pri failed
Dumping resources.language-hr.pri....

WARNING: Dumping resources.language-hr.pri failed
Dumping resources.language-hu.pri....

WARNING: Dumping resources.language-hu.pri failed
Dumping resources.language-id.pri....

WARNING: Dumping resources.language-id.pri failed
Dumping resources.language-is.pri....

WARNING: Dumping resources.language-is.pri failed
Dumping resources.language-it.pri....

WARNING: Dumping resources.language-it.pri failed
Dumping resources.language-ja.pri....

WARNING: Dumping resources.language-ja.pri failed
Dumping resources.language-ka.pri....

WARNING: Dumping resources.language-ka.pri failed
Dumping resources.language-kk.pri....

WARNING: Dumping resources.language-kk.pri failed
Dumping resources.language-ko.pri....

WARNING: Dumping resources.language-ko.pri failed
Dumping resources.language-lt.pri....

WARNING: Dumping resources.language-lt.pri failed
Dumping resources.language-lv.pri....

WARNING: Dumping resources.language-lv.pri failed
Dumping resources.language-ms.pri....

WARNING: Dumping resources.language-ms.pri failed
Dumping resources.language-nb.pri....

WARNING: Dumping resources.language-nb.pri failed
Dumping resources.language-nl.pri....

WARNING: Dumping resources.language-nl.pri failed
Dumping resources.language-nn.pri....

WARNING: Dumping resources.language-nn.pri failed
Dumping resources.language-pl.pri....

WARNING: Dumping resources.language-pl.pri failed
Dumping resources.language-pt.pri....

WARNING: Dumping resources.language-pt.pri failed
Dumping resources.language-qps-ploc.pri....

WARNING: Dumping resources.language-qps-ploc.pri failed
Dumping resources.language-qps-ploca.pri....

WARNING: Dumping resources.language-qps-ploca.pri failed
Dumping resources.language-qps-plocm.pri....

WARNING: Dumping resources.language-qps-plocm.pri failed
Dumping resources.language-ro.pri....

WARNING: Dumping resources.language-ro.pri failed
Dumping resources.language-ru.pri....

WARNING: Dumping resources.language-ru.pri failed
Dumping resources.language-sk.pri....

WARNING: Dumping resources.language-sk.pri failed
Dumping resources.language-sl.pri....

WARNING: Dumping resources.language-sl.pri failed
Dumping resources.language-sq.pri....

WARNING: Dumping resources.language-sq.pri failed
Dumping resources.language-sr-cyrl.pri....

WARNING: Dumping resources.language-sr-cyrl.pri failed
Dumping resources.language-sr-latn.pri....

WARNING: Dumping resources.language-sr-latn.pri failed
Dumping resources.language-sv.pri....

WARNING: Dumping resources.language-sv.pri failed
Dumping resources.language-th.pri....

WARNING: Dumping resources.language-th.pri failed
Dumping resources.language-tr.pri....

WARNING: Dumping resources.language-tr.pri failed
Dumping resources.language-uk.pri....

WARNING: Dumping resources.language-uk.pri failed
Dumping resources.language-vi.pri....

WARNING: Dumping resources.language-vi.pri failed
Dumping resources.language-zh-hans.pri....

WARNING: Dumping resources.language-zh-hans.pri failed
Dumping resources.language-zh-hant.pri....

WARNING: Dumping resources.language-zh-hant.pri failed
Dumping resources.pri....

WARNING: Dumping resources.pri failed
Dumping resources.scale-100.pri....

WARNING: Dumping resources.scale-100.pri failed
Dumping resources.scale-125.pri....

WARNING: Dumping resources.scale-125.pri failed
Dumping resources.scale-150.pri....

WARNING: Dumping resources.scale-150.pri failed
Dumping resources.scale-400.pri....

WARNING: Dumping resources.scale-400.pri failed
Dumping resources....

WARNING: !!!STOP HERE FOR DEBUG!!!
Run  makepri.exe new /pr .\priinfo /cf .\xml\priconfig.xml /of .\resources.pri /mn .\AppxManifest.xml /o at command line!!!

PS C:\Users\MCDeltaT\Downloads\WSA_2302.40000.8.0_x64_Release-Nightly-with-magisk-981ccabb(25210)-canary-MindTheGapps-13.0-RemovedAmazon> ./makepri.exe new /pr .\priinfo /cf .\xml\priconfig.xml /of .\resources.pri /mn .\AppxManifest.xml /o
Index Pass Completed.

Finished building
Version: 1.0
Resource Map Name: MicrosoftCorporationII.WindowsSubsystemForAndroid
Named Resources: 0
Resource Candidates: 0
Successfully Completed
PS C:\Users\MCDeltaT\Downloads\WSA_2302.40000.8.0_x64_Release-Nightly-with-magisk-981ccabb(25210)-canary-MindTheGapps-13.0-RemovedAmazon>

**Comment by Almighty188** [comment]
Output using MakePri.debug.ps1 from https://github.com/LSPosed/MagiskOnWSALocal/issues/450#issuecomment-1483920984
![image](https://user-images.githubusercontent.com/78993393/227742314-f2215e41-c316-4273-ab92-55acc2028345.png)

**Comment by Howard20181** [comment]
Run this, you may need to regenerate WSA.
[MakePri.debug.ps1.txt](https://github.com/LSPosed/MagiskOnWSALocal/files/11070186/MakePri.debug.ps1.txt)
It should be
![image](https://user-images.githubusercontent.com/40033067/227742378-a77416ed-5848-4b18-977b-e11225fdecea.png)

**Comment by Almighty188** [comment]
Output using MakePri.debug.ps1 from https://github.com/LSPosed/MagiskOnWSALocal/issues/450#issuecomment-1483924015
![image](https://user-images.githubusercontent.com/78993393/227742947-8cfb3d88-fdc9-44a2-8e97-3958706f53dd.png)

**Comment by MustardChef** [comment]
I also get the same error code as @Almighty188

**Comment by Howard20181** [comment]
Can you try to dump one of the `pri` manually?
E.g. `.\makepri.exe dump /if .\pri\resources.language-zh-hans.pri /o /es .\pri\resources.pri /of .\priinfo\resources.language-zh-hans.pri.xml /dt detailed`

**Comment by Almighty188** [comment]
PS C:\Users\vince\Desktop\Windows Subsystem for Android\MagiskOnWSALocal\output\WSA_2302.40000.8.0_x64_Release-Nightly-with-magisk-25.2(25200)-stable-MindTheGapps-13.0> .\makepri.exe dump /if .\pri\resources.language-zh-hans.pri /o /es .\pri\resources.pri /of .\priinfo\resources.language-zh-hans.pri.xml /dt detailed
ERROR: PRI175: 0x80004005 - Dump
ERROR: PRI175: 0x80004005 - MakePri failed with error: Unspecified error

PS C:\Users\vince\Desktop\Windows Subsystem for Android\MagiskOnWSALocal\output\WSA_2302.40000.8.0_x64_Release-Nightly-with-magisk-25.2(25200)-stable-MindTheGapps-13.0>

**Comment by Almighty188** [comment]
PS C:\Users\vince\Desktop\Windows Subsystem for Android\MagiskOnWSALocal\output\WSA_2302.40000.8.0_x64_Release-Nightly-with-magisk-25.2(25200)-stable-MindTheGapps-13.0> .\makepri.exe dump /if .\pri\resources.language-zh-hant.pri /o /es .\pri\resources.pri /of .\priinfo\resources.language-zh-hans.pri.xml /dt detailed
ERROR: PRI175: 0x80004005 - Dump
ERROR: PRI175: 0x80004005 - MakePri failed with error: Unspecified error

PS C:\Users\vince\Desktop\Windows Subsystem for Android\MagiskOnWSALocal\output\WSA_2302.40000.8.0_x64_Release-Nightly-with-magisk-25.2(25200)-stable-MindTheGapps-13.0>

**Comment by Almighty188** [comment]
PS C:\Users\vince\Desktop\Windows Subsystem for Android\MagiskOnWSALocal\output\WSA_2302.40000.8.0_x64_Release-Nightly-with-magisk-25.2(25200)-stable-MindTheGapps-13.0> .\makepri.exe dump /if .\pri\resources.language-zh-hant.pri /o /es .\pri\resources.pri /of .\priinfo\resources.language-zh-hant.pri.xml /dt detailed
ERROR: PRI175: 0x80004005 - Dump
ERROR: PRI175: 0x80004005 - MakePri failed with error: Unspecified error

PS C:\Users\vince\Desktop\Windows Subsystem for Android\MagiskOnWSALocal\output\WSA_2302.40000.8.0_x64_Release-Nightly-with-magisk-25.2(25200)-stable-MindTheGapps-13.0>

**Comment by Howard20181** [comment]
What the size of `.\pri\resources.language-zh-hant.pri` and `.\pri\resources.pri`?
For me is 11KB and 87KB

**Comment by Almighty188** [comment]
![image](https://user-images.githubusercontent.com/78993393/227743445-83f48e4d-296b-4f4c-9a6e-e2497a649424.png)

**Comment by Howard20181** [comment]
`.\pri\resources.pri`
![image](https://user-images.githubusercontent.com/40033067/227743511-4e40bb43-f471-4754-bfcc-18d1e8aee27e.png)

**Comment by Howard20181** [comment]
What the size of `resources.pri` in the root of the WSA before running any scripts?

**Comment by Howard20181** [comment]
In 2203.40000.8
It should be 87KB

**Comment by MustardChef** [comment]
> In 2203.40000.8 It should be 87KB

It is indeed 87KB

**Comment by Almighty188** [comment]
Yes, it is 87KB as seen in https://github.com/LSPosed/MagiskOnWSALocal/issues/450#issuecomment-1483916464 posted earlier.

**Comment by Howard20181** [comment]
Try to dump one pri before any scripts be run.
`.\makepri.exe dump /if .\pri\resources.language-zh-hans.pri /o /es .\resources.pri /of .\resources.language-zh-hans.pri.xml /dt detailed`

**Comment by Howard20181** [comment]
Should be 
```
Output File at .\resources.language-zh-hans.pri.xml
Successfully Completed
```

**Comment by Almighty188** [comment]
![image](https://user-images.githubusercontent.com/78993393/227744067-a2654271-456e-47a4-b47b-42f082b48fb8.png)

**Comment by MustardChef** [comment]
I also get the same message 
![image](https://user-images.githubusercontent.com/68516357/227744203-9ec87831-2261-4391-a05b-0af1b9644b72.png)

**Comment by Howard20181** [comment]
Why did it fail to dump before?
Try this
[MakePri.debug.ps1.txt](https://github.com/LSPosed/MagiskOnWSALocal/files/11070318/MakePri.debug.ps1.txt)
Check if dumps success (check priinfo folder)

**Comment by Howard20181** [comment]
If dumps success the exit code should be 0.

**Comment by Howard20181** [comment]
If dumps success run `makepri.exe new /pr .\priinfo /cf .\xml\priconfig.xml /of .\pri\resources.pri /mn .\AppxManifest.xml /o`

**Comment by MustardChef** [comment]
> If dumps success the exit code should be 0.

Exit code still shows -2147024809 and still nothing inside the priinfo folder

**Comment by Howard20181** [comment]
Does the size of `.\pri\resources.pri` same as `.\resources.pri`? It's 87KB.

**Comment by Almighty188** [comment]
Output using MakePri.debug.ps1 from https://github.com/LSPosed/MagiskOnWSALocal/issues/450#issuecomment-1483932655
![image](https://user-images.githubusercontent.com/78993393/227744757-5d6241f0-4f39-41b3-aa40-cceb90099b07.png)

**Comment by Almighty188** [comment]
Output using MakePri.debug.ps1 from https://github.com/LSPosed/MagiskOnWSALocal/issues/450#issuecomment-1483932655

![image](https://user-images.githubusercontent.com/78993393/227744813-666541f5-b11d-4a60-95a1-047fbaa88d05.png)

**Comment by Howard20181** [comment]
Now MakePri.ps1 does the following:

Copy `.\resources.pri` to `.\pri\resources.pri` to make a backup of the original file.
This time the two `pri` should be 87KB.


Try to create a new `pri` base on the files in `pri` folder, the new pre will overwrite the original one in the root folder ,this way we need to do a backup.

if failed to create from `pri`, try to dump all `pri` files in `pri` folder to `priinfo`.

This time `.\pri\resources.pri` should be 87KB.
Dumping `pri` for another language executes English needs based on the original one, this time we need to use the backup one in the `pri` folder. <- We failed on this step. So the backup one corrupted?

then create a new `pri` base on the files in `priinfo` folder

**Comment by Almighty188** [comment]
Yes, because before I did the last MakePri.debug.ps1 - I backed up the resources.pri to resources.pri.orig just in case as seen here:
![image](https://user-images.githubusercontent.com/78993393/227745282-b511ac44-482d-4f30-afb7-22c11bc6bd79.png)

My backup of .\resources.pri as .resources.pri.orig is identical to the backup one in .\pri\resources.pri
![image](https://user-images.githubusercontent.com/78993393/227745369-d0d084da-0979-42d8-99d4-c842e3aa2756.png)

**Comment by Howard20181** [comment]
One possible reason why the first copy step did not complete is that `Copy-Item` is non-blocking, so a `| Out-Null` was added to wait for it to complete, but I saw your feedback that `. \pri\resources.pri` is 87KB in size, the backup should be completed.

**Comment by Howard20181** [comment]
This should success.
`.\makepri.exe dump /if .\pri\resources.language-zh-hans.pri /o /es .\pri\resources.pri /of .\resources.language-zh-hans.pri.xml /dt detailed`

Means
dump per-language pri base on the original `.\pri\resources.pri` backup to `.\resources.language-zh-hans.pri.xml`

**Comment by Almighty188** [comment]
![image](https://user-images.githubusercontent.com/78993393/227745696-fbe6f8eb-f0df-41e0-a541-956b756830f6.png)

**Comment by Howard20181** [comment]
Why it failed in the script and success manually?

**Comment by Howard20181** [comment]
Try this
[MakePri.debug.ps1.txt](https://github.com/LSPosed/MagiskOnWSALocal/files/11070370/MakePri.debug.ps1.txt)
![image](https://user-images.githubusercontent.com/40033067/227745942-90c1e245-5b79-416b-9285-dc673353c5a1.png)

**Comment by Howard20181** [comment]
Try this
[MakePri.debug.ps1.txt](https://github.com/LSPosed/MagiskOnWSALocal/files/11070383/MakePri.debug.ps1.txt)
It may be caused by a space in the path, which is now enclosed in quotes.

**Comment by Almighty188** [comment]
> Try this [MakePri.debug.ps1.txt](https://github.com/LSPosed/MagiskOnWSALocal/files/11070383/MakePri.debug.ps1.txt) It may be caused by a space in the path, which is now enclosed in quotes.

Output using MakePri.debug.ps1 after deleting the priinfo folder and copying .\pri\resources.pri to .\resources.pri but did not regenerate WSA:
![image](https://user-images.githubusercontent.com/78993393/227746385-fed48a03-dd9d-43a3-9452-ec5b645eee7e.png)
![image](https://user-images.githubusercontent.com/78993393/227746419-c091f873-7a43-4e2a-87fc-13f1940b45dd.png)
![image](https://user-images.githubusercontent.com/78993393/227746472-6b29299f-e3a0-46b1-a7b7-45b22589ff58.png)

**Comment by Howard20181** [comment]
Seems like this stupid problem is finally fixed, my bad.

**Comment by MustardChef** [comment]
Seems to be working now.

**Comment by Howard20181** [comment]
Check https://github.com/LSPosed/MagiskOnWSALocal/commit/e3e9c0adb810645c5e2494e1020935d6b089fd07

**Comment by MustardChef** [comment]
> Check [e3e9c0a](https://github.com/LSPosed/MagiskOnWSALocal/commit/e3e9c0adb810645c5e2494e1020935d6b089fd07)

The error is no longer encountered and WSA installs normally. Thank you Almighty188 and Howard20181 for all the help

**Comment by Howard20181** [comment]
Now I switch to relative path, can you confirm if it works properly?
https://github.com/LSPosed/MagiskOnWSALocal/commit/2e02381b9addf70044e5464fab3c58dd308d584b

**Comment by MustardChef** [comment]
> Now I switch to relative path, can you confirm if it works properly? [2e02381](https://github.com/LSPosed/MagiskOnWSALocal/commit/2e02381b9addf70044e5464fab3c58dd308d584b)

Yes, I can confirm that I encounter no problems and it seems to work properly.

**Comment by Almighty188** [comment]
> 

WSA installs properly, but this time, both the Magisk and Google Play Store loads and then exits.  Was able to start both Magisk and Google Play Store manually.
